services:
  task-db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      retries: 5
      timeout: 5s

  redis:
    image: redis/redis-stack:latest
    restart: always
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - redis_data_dev:/var/lib/redis/data
    ports:
      - "6379:6379"
      - "8001:8001"
    env_file: .env

  celery:
    build: .
    command: celery -A tasks worker --loglevel=info
    depends_on:
      - redis
      - api
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      # REDIS_PASSWORD: sasaki19
    env_file: .env
    volumes:
      - .:/backend

  api:
    build: .
    depends_on:
      task-db:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_HOST: redis
    ports:
      - "8000:8000"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    env_file: .env
    volumes:
      - .:/backend

volumes:
  postgres_data_dev:
  redis_data_dev:
