version: '3.12'

services:
  task-db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file: .env

  redis:
    image: redis/redis-stack:latest
    restart: always
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - redis_data:/var/lib/redis/data
    ports:
      - "6379:6379"
      - "8001:8001"
    env_file: .env
  
  api:
    build: .
    depends_on:
      - task-db
      - redis
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "8000:8000"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    env_file: .env

volumes:
  postgres_data:
  redis_data: