"""Task and User modified to have one assigned

Revision ID: 0ca9a9a1726e
Revises: 5128ff2bed08
Create Date: 2026-01-13 15:15:37.546684

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0ca9a9a1726e"
down_revision: Union[str, None] = "5128ff2bed08"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task", sa.Column("assigned_user_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_task_assigned_user_id"), "task", ["assigned_user_id"], unique=False
    )
    op.create_foreign_key(None, "task", "user", ["assigned_user_id"], ["user_id"])
    op.drop_table("tasks_user")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "task", type_="foreignkey")
    op.drop_index(op.f("ix_task_assigned_user_id"), table_name="task")
    op.drop_column("task", "assigned_user_id")
    op.create_table(
        "tasks_user",
        sa.Column("task_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"], ["task.task_id"], name="tasks_user_task_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.user_id"], name="tasks_user_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("task_id", "user_id", name="tasks_user_pkey"),
    )
    # ### end Alembic commands ###
