"""empty message

Revision ID: 4033d9ff7961
Revises: da1879cc255c
Create Date: 2025-05-07 17:35:49.047343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4033d9ff7961'
down_revision: Union[str, None] = 'da1879cc255c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'number')
    # ### end Alembic commands ###
