"""Agregar roles y permisos

Revision ID: 42e939bce2ae
Revises: 
Create Date: 2025-04-15 17:08:57.482672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42e939bce2ae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_user', sa.Column('role', sa.Enum('ADMIN', 'EDITOR', 'MEMBER', name='group_role'), nullable=False, server_default='MEMBER'))
    op.add_column('project_user', sa.Column('permission', sa.Enum('ADMIN', 'WRITE', 'READ', name='project_permission'), nullable=False, server_default='WRITE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_user', 'permission')
    op.drop_column('group_user', 'role')
    # ### end Alembic commands ###
