"""empty message

Revision ID: 4ea1d38c82ed
Revises: e324270afb11
Create Date: 2025-05-15 14:12:33.554364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '4ea1d38c82ed'
down_revision: Union[str, None] = 'e324270afb11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
        """Upgrade schema."""
        # ### commands auto generated by Alembic - please adjust! ###
        op.create_table('session',
            sa.Column('jti', sa.String(length=36), nullable=False),  # UUID como PK
            sa.Column('sub', sa.String(length=128), nullable=False),  # Longitud definida
            sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
            sa.Column('use_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
            sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
            sa.Column('expires_at', sa.DateTime(), nullable=False),
            sa.PrimaryKeyConstraint('jti'),
            sa.Index('ix_session_sub_is_active', 'sub', 'is_active')  # Índice compuesto
        )

    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_sub_is_active'), table_name='session')
    op.drop_table('session')
    # ### end Alembic commands ###