"""agregado eliminacion en labels

Revision ID: 511f432a6f92
Revises: ad7bba107fd2
Create Date: 2025-06-02 17:20:09.903378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '511f432a6f92'
down_revision: Union[str, None] = 'ad7bba107fd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
FK_TASKLABELLINK_TASK_NAME = 'tasklabellink_task_id_fkey'

def upgrade() -> None:
    """Upgrade schema.""" 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_comments', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.drop_column('task_comments', 'is_deletec')
    
    op.drop_constraint(FK_TASKLABELLINK_TASK_NAME, 'tasklabellink', type_='foreignkey')
    op.create_foreign_key(
        FK_TASKLABELLINK_TASK_NAME,      # Nombre de la nueva FK
        'tasklabellink',                 # Tabla que tiene la FK
        'task',                          # Tabla a la que referencia
        ['task_id'],                     # Columna en 'tasklabellink'
        ['task_id'],                     # Columna en 'task'
        ondelete='CASCADE'               # ¡Esto es lo nuevo!
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_comments', sa.Column('is_deletec', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('task_comments', 'is_deleted')

    op.drop_constraint(FK_TASKLABELLINK_TASK_NAME, 'tasklabellink', type_='foreignkey')
    op.create_foreign_key(
        FK_TASKLABELLINK_TASK_NAME,      # Mismo nombre
        'tasklabellink',                 # Tabla que tiene la FK
        'task',                          # Tabla a la que referencia
        ['task_id'],                     # Columna en 'tasklabellink'
        ['task_id'],                     # Columna en 'task'
        # NO ondelete='CASCADE' para el downgrade, o la política anterior si la conoces
    )
    # ### end Alembic commands ###
