"""empty message

Revision ID: 6a0c4820346e
Revises: 8cac2b8b6ff2
Create Date: 2025-05-07 17:27:01.510829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a0c4820346e'
down_revision: Union[str, None] = '8cac2b8b6ff2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('group_user_user_id_fkey', 'group_user', type_='foreignkey')
    op.drop_constraint('group_user_group_id_fkey', 'group_user', type_='foreignkey')
    op.create_foreign_key(None, 'group_user', 'group', ['group_id'], ['group_id'])
    op.create_foreign_key(None, 'group_user', 'user', ['user_id'], ['user_id'])
    op.drop_constraint('project_user_project_id_fkey', 'project_user', type_='foreignkey')
    op.drop_constraint('project_user_user_id_fkey', 'project_user', type_='foreignkey')
    op.create_foreign_key(None, 'project_user', 'user', ['user_id'], ['user_id'])
    op.create_foreign_key(None, 'project_user', 'project', ['project_id'], ['project_id'])
    op.drop_constraint('projectchat_project_id_fkey', 'projectchat', type_='foreignkey')
    op.create_foreign_key(None, 'projectchat', 'project', ['project_id'], ['project_id'])
    op.drop_constraint('tasks_user_user_id_fkey', 'tasks_user', type_='foreignkey')
    op.drop_constraint('tasks_user_task_id_fkey', 'tasks_user', type_='foreignkey')
    op.create_foreign_key(None, 'tasks_user', 'task', ['task_id'], ['task_id'])
    op.create_foreign_key(None, 'tasks_user', 'user', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks_user', type_='foreignkey')
    op.drop_constraint(None, 'tasks_user', type_='foreignkey')
    op.create_foreign_key('tasks_user_task_id_fkey', 'tasks_user', 'task', ['task_id'], ['task_id'], ondelete='CASCADE')
    op.create_foreign_key('tasks_user_user_id_fkey', 'tasks_user', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'projectchat', type_='foreignkey')
    op.create_foreign_key('projectchat_project_id_fkey', 'projectchat', 'project', ['project_id'], ['project_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'project_user', type_='foreignkey')
    op.drop_constraint(None, 'project_user', type_='foreignkey')
    op.create_foreign_key('project_user_user_id_fkey', 'project_user', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key('project_user_project_id_fkey', 'project_user', 'project', ['project_id'], ['project_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'group_user', type_='foreignkey')
    op.drop_constraint(None, 'group_user', type_='foreignkey')
    op.create_foreign_key('group_user_group_id_fkey', 'group_user', 'group', ['group_id'], ['group_id'], ondelete='CASCADE')
    op.create_foreign_key('group_user_user_id_fkey', 'group_user', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
