"""empty message

Revision ID: 7812ce6a0d81
Revises: 42e939bce2ae
Create Date: 2025-04-21 16:43:11.153542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7812ce6a0d81'
down_revision: Union[str, None] = '42e939bce2ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projectchat',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_index(op.f('ix_projectchat_project_id'), 'projectchat', ['project_id'], unique=False)
    op.create_index(op.f('ix_projectchat_user_id'), 'projectchat', ['user_id'], unique=False)
    op.create_index(op.f('ix_project_group_id'), 'project', ['group_id'], unique=False)
    op.create_index(op.f('ix_task_project_id'), 'task', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_project_id'), table_name='task')
    op.drop_index(op.f('ix_project_group_id'), table_name='project')
    op.drop_index(op.f('ix_projectchat_user_id'), table_name='projectchat')
    op.drop_index(op.f('ix_projectchat_project_id'), table_name='projectchat')
    op.drop_table('projectchat')
    # ### end Alembic commands ###
