"""empty message

Revision ID: aaf7bb5ea051
Revises: 4ea1d38c82ed
Create Date: 2025-05-18 20:52:30.277421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'aaf7bb5ea051'
down_revision: Union[str, None] = '4ea1d38c82ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_comments',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('is_deletec', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.task_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_index(op.f('ix_task_comments_task_id'), 'task_comments', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_comments_user_id'), 'task_comments', ['user_id'], unique=False)
    op.drop_index('ix_session_sub_is_active', table_name='session')
    op.create_index(op.f('ix_session_sub'), 'session', ['sub'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_sub'), table_name='session')
    op.create_index('ix_session_sub_is_active', 'session', ['sub', 'is_active'], unique=False)
    op.drop_index(op.f('ix_task_comments_user_id'), table_name='task_comments')
    op.drop_index(op.f('ix_task_comments_task_id'), table_name='task_comments')
    op.drop_table('task_comments')
    # ### end Alembic commands ###