"""empty message

Revision ID: ad7bba107fd2
Revises: aaf7bb5ea051
Create Date: 2025-06-01 17:20:16.966910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad7bba107fd2'
down_revision: Union[str, None] = 'aaf7bb5ea051'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

from models.db_models import TypeOfLabel
ENUM_NAME = 'typeoflabel'
enum_values = [f"'{e.value}'" for e in TypeOfLabel]
enum_values_str = ', '.join(enum_values)

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_comments', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.drop_column('task_comments', 'is_deletec')

    op.execute(f"CREATE TYPE {ENUM_NAME} AS ENUM ({enum_values_str})")

    op.create_table('tasklabellink',
        sa.column('task_id', sa.Integer(), sa.ForeignKey('task.task_id'), nullable=False),
        sa.column('label', sa.Enum(TypeOfLabel, name='typeoflabel', create_type=False), nullable=False),
        sa.PrimaryKeyConstraint('task_id', 'label'))
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_comments', sa.Column('is_deletec', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('task_comments', 'is_deleted')
    
    op.drop_table('tasklabellink')
    op.execute(f"DROP TYPE typeoflabel")
    # ### end Alembic commands ###